### ISSUE TITLE
[Visitor Feedback] A bug in the RSS feed

### ISSUE THREAD

**Issue by Hamatti** [rupl/chrisruppel.com#156]
Hey!

I recently added your blog to my RSS reader and noticed today the entries look like this

<img width="759" alt="Screenshot 2023-01-24 at 15 18 18" src="https://user-images.githubusercontent.com/1909996/214318502-31b5a542-1a88-4bbf-a405-891950e28767.png">

(this was for https://chrisruppel.com/blog/eleventy-2-beta/)

**Comment by rupl** [comment]
Howdy, thanks for letting me know 💕 

I took a look at the [W3 validation for the feed](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fchrisruppel.com%2Fblog.xml). And it seems to be some fairly minor templating errors.

I'll fix it up and circle back around, thanks!

**Comment by rupl** [comment]
Yup all good now. Thanks again!
