### ISSUE TITLE
Character Encoding Issue in <picture> Tags

### ISSUE THREAD

**Issue by milsyobtaf** [rupl/chrisruppel.com#36]
There appears to be an encoding issue in your <picture> tags, specifically the `data-comment` attribute. This can be seen in the Thai longboat image located at https://chrisruppel.com/travel/koh-phi-phi-thailand/. Unsure if it is all special characters, however the specific character in question is a colon.

Image (provided by @mattgrill):
![image](https://cloud.githubusercontent.com/assets/606158/14164154/d138677c-f6ca-11e5-86ef-745202fd0b33.png)

**Comment by rupl** [comment]
haha, thanks!

**Comment by rupl** [comment]
this is all YML's fault
