### ISSUE TITLE
Lilypad Arduino

### ISSUE THREAD

**Issue by mikochstr** [rupl/chrisruppel.com#86]
hello sir, i am just curious on how do you code a lilypad arduino? we have a similar project like the turn signal biking jacket but we do not understand the tutorials we have search in the internet and having a hard time to figure out on how to program the lilypad arduino. Hope you message back, it will be a great help. Thanks :)

**Comment by rupl** [comment]
For the [biking jacket project documented on my site](https://chrisruppel.com/blog/lilypad-arduino-biking-jacket/), I used the official Arduino IDE. It can connect to all official products, including the LilyPad Arduino. They have tutorials on their site to guide you through your first-time setup.

* Official link for IDE: https://www.arduino.cc/en/Main/Software
* First-time instructions for LilyPad: https://www.arduino.cc/en/Guide/ArduinoLilyPad

Good luck and have fun with Arduino!
